export const Questions = [
  {
    prompt: "How many time zones are there in Russia?",
    optionA: "12",
    optionB: "9",
    optionC: "5",
    optionD: "11",
    asnwer: "optionD",
  },
  {
    prompt: "Which of the following empires had no written language?",
    optionA: "Roman",
    optionB: "Aztec",
    optionC: "Incan",
    optionD: "Egyptian",
    asnwer: "optionC",
  },
  {
    prompt: "How many days does it take for the Earth to orbit the Sun?",
    optionA: "375",
    optionB: "321",
    optionC: "325",
    optionD: "365",
    asnwer: "optionD",
  },
  {
    prompt: "What color is a ruby?",
    optionA: "Red",
    optionB: "White",
    optionC: "Green",
    optionD: "Black",
    asnwer: "optionA",
  },
  {
    prompt: "Who was the first president of the United States?",
    optionA: "Richard Nixon",
    optionB: "William McKinley",
    optionC: "George Washington",
    optionD: "Jimmy Carter",
    asnwer: "optionC",
  },
  {
    prompt: "How many languages are written from right to left? ",
    optionA: "12",
    optionB: "22",
    optionC: "10",
    optionD: "14",
    asnwer: "optionA",
  },

  {
    prompt: "How many languages are written from right to left? ",
    optionA: "France",
    optionB: "Greece",
    optionC: "Italia",
    optionD: "Tunisia",
    asnwer: "optionB",
  },

  {
    prompt: "Havana is the capital of what country? ",
    optionA: "Argentina",
    optionB: "Angola",
    optionC: "Cuba",
    optionD: "Albania",
    asnwer: "optionC",
  },
  {
    prompt:
      "Demolition of the Berlin wall separating East and West Germany began in what year?",
    optionA: "1999",
    optionB: "1989",
    optionC: "1970",
    optionD: "1968",
    asnwer: "optionB",
  },
  {
    prompt: "Havana is the capital of what country? ",
    optionA: "Argentina",
    optionB: "Angola",
    optionC: "Cuba",
    optionD: "Albania",
    asnwer: "optionC",
  },
];
